### ISSUE TITLE
Nested GroupTerm search returns no matches

### ISSUE THREAD

**Issue by kartiksayani** [nazrulworld/fhirpath#28]
* fhirpath version: 0.10.4
* Python version: 3.9.0
* Operating System: MacOS

### Description
This is not a bug report but a question.

### What I Did
I created a Patient resource with the following content
```json
{
  "resourceType": "Patient",
  "id": "1",
  "name": [
    {
      "given": [
        "John"
      ],
      "family": "Mercer"
    },
    {
      "given": [
        "Alex"
      ],
      "family": "Connor"
    }
  ]
}
```

Then, I tried the following search
```
search_context = SearchContext(engine, "Patient")
# equivalent to /Patient?name=John&name=Connor
params = (("name", "John"), ("name", "Connor"), )
search_tool = Search(search_context, params=params)
bundle = search_tool()
assert bundle.total > 0
```
No documents are matched due to the `nested` wrapper on the top-most `GroupTerm`.

A similar query on HAPI Test Server returns a non-zero response
```
curl -X GET "http://hapi.fhir.org/baseR4/Patient?name=Ajay&name=Mishra&_pretty=true"
```

I could not any relevant documentation or rules around such matches on [FHIR Search](https://www.hl7.org/fhir/search.html).

Is this behavior server specific or something that I may have missed in FHIR specification?

**Comment by nazrulworld** [comment]
@kartiksayani thanks a lot for this issue.
I can regenerate in my local also, will back soon with details.
