### ISSUE TITLE
Switch to Apache License 2.0 ?

### ISSUE THREAD

**Issue by simonvadee** [nazrulworld/fhirpath#29]
The project is currently licensed under GPLv3, which (if I'm not mistaken) makes dependent projects using GPLv3 as well (see https://choosealicense.com/licenses/gpl-3.0/).

We are currently building open-source software on top of fhirpath (and fhir.resources) but we are using the more permissive Apache2 license (like most projects hosted at https://github.com/FHIR or popular projects like https://github.com/hapifhir/hapi-fhir or https://github.com/IBM/FHIR).
Apache2 details (and TLDR) can be found here: https://choosealicense.com/licenses/apache-2.0/
Note that we would not be impacted by other permissive licenses like the MIT License.

I know we already discussed the subject and you seemed to be open to changing the licensing model but this is becoming an issue on our end.

Related: https://github.com/arkhn/fhir-river/issues/281

**Comment by nazrulworld** [comment]
Seems good to me :) we can change the license to Apache 2.0.
If you want you can make a pull request.
